### ISSUE TITLE
Unrecognized country in datapoints

### ISSUE THREAD

**Issue by olga-govor** [ludmilamarian/MapWiT#21]
Change datapoint aniSowmya.json
Country The Bahamas should be changed to Bahamas

**Comment by ludmilamarian** [comment]
Hi @olga-govor! I can see `The Bahamas` on the map. It's small, so not very obvious, but it is taken into account.

**Comment by olga-govor** [comment]
Ok, I've just checked on the list of countries and there its Bahamas, but not The Bahamas

**Comment by ludmilamarian** [comment]
You are correct! I am not exactly sure what is the list of countries that `plotly` uses, that is a bit the problem, but I will check better. But, I can see the point on the map (screenshot attached). I see that ISO has it listed like this: `(the) Bahamas` https://www.iso.org/obp/ui/#iso:code:3166:BS so the standard is treating `the` as optional.

<img width="1075" alt="Screenshot 2019-11-29 at 12 07 36" src="https://user-images.githubusercontent.com/5615123/69865525-a249c680-12a1-11ea-9b18-9f2e1293ccee.png">
